-- Add all 37 ACT projects from main website to Empathy Ledger
-- This allows any project to have featured storytellers/stories in the future

-- Insert all 37 projects (will skip the 9 that already exist due to ON CONFLICT)
INSERT INTO act_projects (slug, title, organization_name, focus_areas, themes, description, website_url, project_site_url, is_active)
VALUES
  -- Existing 9 projects (will be skipped by ON CONFLICT)
  ('justicehub', 'JusticeHub', 'JusticeHub', ARRAY['Justice', 'Youth', 'Technology', 'Advocacy'], ARRAY['Community Healing', 'Systems Change', 'Youth Empowerment'], 'Youth justice advocacy platform connecting young people with support services and sharing their stories.', 'https://act.place/projects/justicehub', 'https://justicehub.org', TRUE),
  ('goods', 'Goods.', 'Goods.', ARRAY['Environment', 'Circular Economy', 'Asset Management'], ARRAY['Sustainability', 'Resource Tracking', 'Community Assets'], 'Asset register and circular economy platform for tracking and sharing community resources.', 'https://act.place/projects/goods', NULL, TRUE),
  ('bg-fit', 'BG Fit', 'BG Fit', ARRAY['Health', 'Wellness', 'Community'], ARRAY['Physical Wellbeing', 'Social Connection', 'Active Living'], 'Community fitness and wellbeing initiative promoting active, healthy lifestyles.', 'https://act.place/projects/bg-fit', NULL, TRUE),
  ('the-harvest', 'The Harvest', 'The Harvest', ARRAY['Agriculture', 'Heritage', 'Community', 'Education'], ARRAY['Cultural Preservation', 'Sustainable Farming', 'Intergenerational Learning'], 'Heritage farm and community hub preserving agricultural traditions and promoting sustainable practices.', 'https://act.place/projects/the-harvest', 'https://theharvest.org.au', TRUE),
  ('act-farm', 'ACT Farm', 'ACT Farm', ARRAY['Conservation', 'Research', 'Arts', 'Wellness'], ARRAY['Regenerative Agriculture', 'Creative Practice', 'Therapeutic Landscapes'], 'Research and residency farm focused on regenerative practices and creative conservation.', 'https://act.place/projects/act-farm', 'https://actfarm.org.au', TRUE),
  ('junes-patch', 'June''s Patch', 'ACT Farm', ARRAY['Health', 'Agriculture', 'Therapy', 'Nature'], ARRAY['Therapeutic Landscapes', 'Social Prescribing', 'Nature Connection'], 'Therapeutic garden and nature-based health program offering social prescribing and healing spaces.', 'https://act.place/projects/junes-patch', 'https://actfarm.org.au/junes-patch', TRUE),
  ('place-based-policy-lab', 'Place-Based Policy Lab', 'ACT', ARRAY['Policy', 'Research', 'Community Development', 'Systems Change'], ARRAY['Evidence-Based Practice', 'Community-Led Policy', 'Participatory Research'], 'Research initiative developing evidence-based, community-informed policies for place-based change.', 'https://act.place/projects/place-based-policy-lab', NULL, TRUE),
  ('local-seasonal-supply', 'Local Seasonal Supply', 'ACT Farm', ARRAY['Agriculture', 'Food Systems', 'Local Economy'], ARRAY['Food Security', 'Regenerative Farming', 'Community Provisioning'], 'Local food network connecting regenerative farms with community buyers for seasonal produce.', 'https://act.place/projects/local-seasonal-supply', NULL, TRUE),
  ('empathy-ledger', 'Empathy Ledger', 'Empathy Ledger', ARRAY['Storytelling', 'Technology', 'Community', 'Data Sovereignty'], ARRAY['Narrative Power', 'Digital Ethics', 'Community Voice'], 'AI-enhanced storytelling platform centering community voices while preserving data sovereignty.', 'https://act.place/projects/empathy-ledger', 'https://empathyledger.com', TRUE),

  -- NEW: 28 additional projects from main website
  ('global-laundry-alliance', 'Global Laundry Alliance', 'Global Laundry Alliance', ARRAY['Community dignity', 'Systems change', 'Global collaboration'], ARRAY['Dignity', 'Community Hubs', 'Policy Change'], 'Global Laundry Alliance (GLA) is a collaboration reframing access to laundry as a dignity issue and a basic right. It connects communities and organisations working across homelessness, refugee displacement, and global poverty to co-design practical laundry solutions with lived-experience leadership.', 'https://act.place/projects/global-laundry-alliance', NULL, TRUE),

  ('diagrama-spain', 'Diagrama Spain/England Journey', 'Diagrama', ARRAY['Youth justice', 'International learning', 'Therapeutic practice'], ARRAY['Youth Justice', 'International Exchange', 'Therapeutic Approaches'], 'Learning from Spain''s youth justice transformation. Standing in Diagrama''s La Zarza centre, witnessing staff and young people engaged in genuine conversation, sharing laughter, navigating conflict with respect. No power plays. No dehumanisation. Just authentic connection.', 'https://act.place/projects/diagrama-spain', NULL, TRUE),

  ('green-harvest-witta', 'Green Harvest Witta', 'Green Harvest Witta', ARRAY['Sustainability', 'Community knowledge', 'Innovation hub'], ARRAY['Community Innovation', 'Sustainability', 'Knowledge Sharing'], 'Green Harvest Witta has a "next chapter" vision. Transforming its legacy of sustainability and community knowledge-sharing into a living, community-led innovation hub.', 'https://act.place/projects/green-harvest-witta', NULL, TRUE),

  ('gold-phone', 'Gold.Phone', 'A Curious Tractor', ARRAY['Community engagement', 'Storytelling', 'Creative technology'], ARRAY['Creative Technology', 'Community Connection', 'Storytelling'], 'The Gold.Phone is an experimental communication tool designed to explore how items from our past can be repurposed to create new levels of community engagement and understanding. This remodelled pay phone merges nostalgic elements with modern digital technology to provide a unique platform for sharing stories, thoughts, and messages.', 'https://act.place/projects/gold-phone', NULL, TRUE),

  ('fishers-oysters', 'Fishers Oysters', 'Fishers Oysters', ARRAY['Indigenous-led', 'Regenerative practice', 'Economic sovereignty'], ARRAY['Indigenous Leadership', 'Aquaculture', 'Ecosystem Restoration'], 'Fishers Oysters is an Indigenous-led aquaculture project to reclaim and restore Moreton Bay''s oyster reefs, blending cultural knowledge with regenerative practice to rebuild ecosystems and create long-term economic sovereignty for Quandamooka communities.', 'https://act.place/projects/fishers-oysters', NULL, TRUE),

  ('goods-on-country', 'Goods on Country', 'A Curious Tractor', ARRAY['Remote Communities', 'Essential Goods', 'Community Partnership'], ARRAY['Indigenous Partnership', 'Remote Access', 'Essential Services'], 'Every Australian deserves access to quality household essentials, regardless of where they live. We partner with Aboriginal Elders and Traditional Owners to deliver durable beds, washing machines, and furniture to remote communities.', 'https://act.place/projects/goods-on-country', NULL, TRUE),

  ('bg-fit-mount-isa', 'BG Fit Mount Isa', 'BG Fit', ARRAY['Youth engagement', 'Lived experience leadership', 'Community trust'], ARRAY['Youth Engagement', 'Community Leadership', 'Physical Activity'], 'Community connection through fitness and culture. Brodie Germaine, a local leader with lived experience of the streets he now serves, runs a gym that pulses with energy as young people engage in purposeful activity.', 'https://act.place/projects/bg-fit-mount-isa', NULL, TRUE),

  ('quandamooka-justice-strategy', 'Quandamooka Justice and Healing Strategy', 'MMEIC', ARRAY['Justice reinvestment', 'Elder leadership', 'Community healing'], ARRAY['Justice Reinvestment', 'Indigenous Leadership', 'Community Healing'], 'Elder-led justice reinvestment on Country. The Minjerribah Moorgumpin Elders-In-Council Corporation (MMEIC) officially launched their work towards developing the Quandamooka Justice and Healing Strategy. Guided by the MMEIC Elders, the justice reinvestment team have been tasked with developing the Quandamooka Justice and Healing Strategy for the region.', 'https://act.place/projects/quandamooka-justice-strategy', NULL, TRUE),

  ('smart-recovery-gp-kits', 'SMART Recovery GP Kits', 'SMART Recovery', ARRAY['Primary care', 'Addiction support', 'Early intervention'], ARRAY['Healthcare Integration', 'Addiction Support', 'Primary Care'], 'The GP Kits are a set of physical "activation tools" designed to make SMART Recovery easy to refer to from primary care. They use simple, memorable artefacts (notepads, sandtimers, and coasters) to lower the friction for GPs to start a conversation and make a quick referral.', 'https://act.place/projects/smart-recovery-gp-kits', NULL, TRUE),

  ('goods-tennant-creek', 'Goods Tennant Creek Journey', 'A Curious Tractor', ARRAY['Traditional Ownership', 'Co-design', 'Mutual transformation'], ARRAY['Co-Design', 'Indigenous Partnership', 'Traditional Knowledge'], 'Co-creating with Traditional Owners. What emerged between A Curious Tractor and Traditional Owner Dianne wasn''t merely a transaction of ideas, but a tapestry of mutual transformation. As Nicholas Marchesi worked alongside Dianne—crafting beds, learning language for the buttons on an "indestructible washing machine"—we witnessed the dissolution of artificial boundaries between "helper" and "helped."', 'https://act.place/projects/goods-tennant-creek', NULL, TRUE),

  ('oonchiumpa', 'Oonchiumpa', 'Oonchiumpa', ARRAY['Aboriginal-led', 'Youth crisis support', 'Cultural authority'], ARRAY['Indigenous Leadership', 'Youth Support', 'Cultural Practice'], 'Oonchiumpa is an Aboriginal-led initiative in Central Australia focused on creating culturally grounded pathways for young people in crisis, with Elders and local cultural authority guiding what "support" looks like on Country and in town.', 'https://act.place/projects/oonchiumpa', NULL, TRUE),

  ('bupa-tfn-pitch', 'Bupa TFN Healthy People, Healthy Planet', 'The Funding Network', ARRAY['Social enterprise', 'Community health', 'Climate action'], ARRAY['Social Enterprise', 'Environmental Health', 'Community Impact'], 'Three amazing changemakers selected to pitch at our special Healthy People, Healthy Planet event with Bupa Foundation in Melbourne. Championing human and planetary health through social enterprise.', 'https://act.place/projects/bupa-tfn-pitch', NULL, TRUE),

  ('pakkinjalki-kari', 'Pakkinjalki kari (Washing Machine)', 'A Curious Tractor', ARRAY['Co-design', 'Repair culture', 'Community manufacturing'], ARRAY['Indigenous Co-Design', 'Repair Culture', 'Community Manufacturing'], 'Culturally appropriate design on Warumungu Country. We built a culturally appropriate Washing Machine! Through hundreds of hours of conversation, the community asked for something easy to use, appropriate for the environment, easy to repair, and smart. We removed all the buttons and have one "go" button.', 'https://act.place/projects/pakkinjalki-kari', NULL, TRUE),

  ('weave-bed-tennant-creek', 'Weave Bed Design', 'A Curious Tractor', ARRAY['Prototype design', 'Community iteration', 'Repairable goods'], ARRAY['Product Design', 'Community Iteration', 'Repairability'], 'Washable, repairable, community-built. Imagine if you could weave a bed? Designing, iterating and learning with community. Thankful for Jimmy Frank Jupurrurla and his community for embracing the opportunity to re imagine Goods for the community.', 'https://act.place/projects/weave-bed-tennant-creek', NULL, TRUE),

  ('naidoc-week-mount-isa', 'NAIDOC Week Mount Isa', 'BG Fit', ARRAY['Cultural celebration', 'Youth connection', 'Community leadership'], ARRAY['Cultural Celebration', 'Community Connection', 'Indigenous Leadership'], 'Kinship in action with BG Fit. Watch Brodie Germaine move through his community with a microphone like he''s conducting ceremony, not interviews. This isn''t journalism - it''s kinship in action.', 'https://act.place/projects/naidoc-week-mount-isa', NULL, TRUE),

  ('contained', 'CONTAINED', 'JusticeHub', ARRAY['Youth justice', 'Experiential design', 'Community advocacy'], ARRAY['Youth Justice', 'Experiential Design', 'Community Advocacy'], 'CONTAINED is an experiential installation that immerses visitors in the reality of youth detention and the power of community alternatives. Through physical design, storytelling, and data visualization, we make visible the human cost of incarceration and the evidence for community-led solutions.', 'https://act.place/projects/contained', NULL, TRUE),

  ('tomnet', 'TOMNET', 'TOMNET', ARRAY['Mental wellbeing', 'Peer-led support', 'Regional community'], ARRAY['Mental Health', 'Peer Support', 'Community Connection'], 'TOMNET is a community-led network in Toowoomba supporting men over 50 to move from isolation into belonging, purpose, and contribution. The project captures that transformation through authentic, peer-led storytelling.', 'https://act.place/projects/tomnet', NULL, TRUE),

  ('westpac-summit-2025', 'Westpac Summit 2025', 'Westpac', ARRAY['Community engagement', 'Storytelling activation', 'Leadership'], ARRAY['Leadership Development', 'Storytelling', 'Community Engagement'], 'Westpac Summit ''25 — Closing Plenary "Scholar Cards" Activation', 'https://act.place/projects/westpac-summit-2025', NULL, TRUE),

  ('uncle-allan-palm-island-art', 'Uncle Allan Palm Island Art', 'Burrgu Man Barra Art', ARRAY['Cultural sovereignty', 'Indigenous art', 'Digital platform'], ARRAY['Indigenous Art', 'Cultural Sovereignty', 'Digital Storytelling'], 'This website (burrgumanbarraart.com) showcases Uncle Allan''s work, helps attract commissions and collaborators, and strengthens cultural sovereignty by sharing stories on Uncle Allan''s terms.', 'https://act.place/projects/uncle-allan-palm-island-art', 'https://burrgumanbarraart.com', TRUE),

  ('the-confessional', 'The Confessional', 'A Curious Tractor', ARRAY['Safe space', 'Vulnerability', 'Community healing'], ARRAY['Safe Space', 'Vulnerability', 'Community Healing'], 'The Confessional creates safe space for people to share what they''re carrying. Through design, ritual, and careful facilitation, we hold space for vulnerability and truth-telling.', 'https://act.place/projects/the-confessional', NULL, TRUE),

  ('smart-hcp-gp-uplift', 'SMART HCP GP Uplift', 'SMART Recovery', ARRAY['Healthcare integration', 'GP referrals', 'Addiction support'], ARRAY['Healthcare Integration', 'Addiction Support', 'Provider Education'], 'SMART Recovery — GP Uplift (HCP Integration) connects healthcare providers with SMART Recovery tools and pathways, making it easier for GPs to refer patients to evidence-based addiction support.', 'https://act.place/projects/smart-hcp-gp-uplift', NULL, TRUE),

  ('smart-connect', 'SMART Connect', 'SMART Recovery', ARRAY['Peer support', 'Digital pathways', 'Community connection'], ARRAY['Peer Support', 'Digital Access', 'Community Connection'], 'SMART Connect builds digital and physical pathways that help people find SMART Recovery meetings, resources, and community when they need it most.', 'https://act.place/projects/smart-connect', NULL, TRUE),

  ('regional-arts-fellowship', 'Regional Arts Fellowship', 'ACT', ARRAY['Art & technology', 'Agriculture', 'Regional innovation'], ARRAY['Art & Technology', 'Agriculture', 'Regional Innovation'], 'A Curious Tractor x Australian Network for Art & Technology x Agriculture Industry. This fellowship explores the intersection of creative practice, emerging technology, and regenerative agriculture in regional Australia.', 'https://act.place/projects/regional-arts-fellowship', NULL, TRUE),

  ('picc-centre-precinct', 'PICC Centre Precinct', 'PICC', ARRAY['Community space', 'Co-design', 'Palm Island'], ARRAY['Community Design', 'Place-Making', 'Indigenous Community'], 'ACT supported the PICC Centre Precinct project by helping turn an under-used, run-down site into a shared picture of what it could become.', 'https://act.place/projects/picc-centre-precinct', NULL, TRUE),

  ('picc-photo-kiosk', 'PICC Photo Kiosk', 'PICC', ARRAY['Community control', 'Digital tools', 'Cultural storytelling'], ARRAY['Community Control', 'Digital Tools', 'Cultural Storytelling'], 'Building a community-controlled "photo studio" on Palm Island that puts the power of image-making in the hands of community members.', 'https://act.place/projects/picc-photo-kiosk', NULL, TRUE),

  ('picc-elders-hull-river', 'PICC Elders Hull River Trip', 'PICC', ARRAY['Cultural practice', 'Connection to Country', 'Elder leadership'], ARRAY['Cultural Practice', 'Connection to Country', 'Elder Leadership'], 'PICC Elders'' trip to Hull River in October brought Elders back to traditional lands for cultural practice, storytelling, and connection with place.', 'https://act.place/projects/picc-elders-hull-river', NULL, TRUE),

  ('picc-annual-report', 'PICC Annual Report', 'PICC', ARRAY['Indigenous storytelling', 'Community control', 'Accountability'], ARRAY['Indigenous Storytelling', 'Community Control', 'Transparency'], 'This PICC Annual Report project is the home base for producing a community-led annual report for PICC that strengthens Indigenous storytelling and keeps power and narrative control with community.', 'https://act.place/projects/picc-annual-report', NULL, TRUE),

  ('caring-for-those-who-care', 'Caring for Those Who Care', 'ACT', ARRAY['NFP leadership', 'Storytelling', 'Community sector'], ARRAY['Sector Sustainability', 'Leadership Support', 'Community Storytelling'], 'Amplifying Voices of NFP Leaders Across Australia. This project captures the wisdom, challenges, and insights of people leading community organizations on the frontlines of social change.', 'https://act.place/projects/caring-for-those-who-care', NULL, TRUE),

  ('mounty-yarns', 'Mounty Yarns', 'Mounty Yarns', ARRAY['Youth leadership', 'Lived experience', 'Systems change'], ARRAY['Youth Leadership', 'Lived Experience', 'Systems Change'], 'Mounty Yarns is a youth-led base in Mount Druitt that turns lived experience into leadership, creating space for young people to gather, yarn, and influence the systems that shape their lives.', 'https://act.place/projects/mounty-yarns', NULL, TRUE),

  ('designing-for-obsolescence', 'Designing for Obsolescence', 'A Curious Tractor', ARRAY['Circular design', 'Repair culture', 'Product lifecycle'], ARRAY['Circular Economy', 'Sustainable Design', 'Product Lifecycle'], 'Overview — Designing for Obsolescence explores what it means to design products that are built to last, built to be repaired, and built with their end of life in mind.', 'https://act.place/projects/designing-for-obsolescence', NULL, TRUE),

  ('dad-lab-25', 'Dad.Lab.25', 'ACT', ARRAY['Fatherhood', 'Community support', 'Gender equity'], ARRAY['Fatherhood', 'Community Support', 'Gender Equity'], 'Exploring Dad.Lab.25 in Australia. This project creates space for fathers to gather, share experiences, and explore what it means to show up for their kids and communities.', 'https://act.place/projects/dad-lab-25', NULL, TRUE)

ON CONFLICT (slug) DO NOTHING;

-- Summary comment
COMMENT ON TABLE act_projects IS 'All 37 ACT projects are now in Empathy Ledger. Storytellers can opt-in to be featured on any project, and ACT admins can approve which stories/storytellers appear on each project page.';
