// Force dynamic rendering for API routes
export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'

import { createClient } from '@supabase/supabase-js'



const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY
const supabase = createClient(supabaseUrl, supabaseServiceKey)

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id: transcriptId } = await params
    console.log('📄 Exporting transcript:', transcriptId)

    // Get transcript details
    const { data: transcript, error } = await supabase
      .from('transcripts')
      .select(`
        id,
        title,
        transcript_content,
        word_count,
        character_count,
        created_at,
        storyteller_id,
        profiles!transcripts_storyteller_id_fkey (
          full_name,
          display_name
        )
      `)
      .eq('id', transcriptId)
      .single()

    if (error || !transcript) {
      console.error('❌ Transcript not found:', error)
      return NextResponse.json(
        { success: false, error: 'Transcript not found' },
        { status: 404 }
      )
    }

    // Format the export content
    const storytellerName = transcript.profiles?.full_name || transcript.profiles?.display_name || 'Unknown Storyteller'
    const exportDate = new Date().toLocaleDateString()
    
    const exportContent = `
TRANSCRIPT EXPORT
================

Title: ${transcript.title}
Storyteller: ${storytellerName}
Created: ${new Date(transcript.created_at).toLocaleDateString()}
Word Count: ${transcript.word_count || 0}
Character Count: ${transcript.character_count || 0}

Export Date: ${exportDate}
Export ID: ${transcriptId}

--------------------------------------------------------------------------------

TRANSCRIPT CONTENT:

${transcript.transcript_content || 'No content available'}

--------------------------------------------------------------------------------

Generated by Empathy Ledger
Export completed on ${exportDate}
    `.trim()

    // Return as downloadable file
    const blob = new Blob([exportContent], { type: 'text/plain' })
    
    return new NextResponse(blob, {
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename="${transcript.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.txt"`
      }
    })

  } catch (error) {
    console.error('❌ Error exporting transcript:', error)
    return NextResponse.json(
      { 
        success: false, 
        error: 'Failed to export transcript',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    )
  }
}