-- Direct database insert to test Sprint 2 fields
-- This bypasses RLS to verify schema changes are working

INSERT INTO public.stories (
  title,
  content,
  excerpt,
  storyteller_id,
  author_id,
  tenant_id,
  story_type,
  location,
  tags,
  cultural_sensitivity_level,
  requires_elder_review,
  privacy_level,
  is_public,
  status,
  enable_ai_processing,
  notify_community,
  language,
  has_explicit_consent,
  video_link
) VALUES (
  'Sprint 2 Direct Insert Test',
  'This is a comprehensive test with enough words to verify that the word count trigger is working correctly. We need at least 30 words to see a reading time of 1 minute calculated automatically by the database trigger.',
  'A test story to verify Sprint 2 schema changes',
  'ee202ace-d18b-4d9f-bf2a-c700eb3480fa',
  'ee202ace-d18b-4d9f-bf2a-c700eb3480fa',
  (SELECT tenant_id FROM public.profiles WHERE id = 'ee202ace-d18b-4d9f-bf2a-c700eb3480fa'),
  'text',
  'Traditional Territory',
  ARRAY['test', 'sprint2', 'direct-insert'],
  'sensitive',
  false,
  'public',
  true,
  'draft',
  true,
  true,
  'en',
  true,
  NULL
)
RETURNING
  id,
  title,
  word_count,
  reading_time,
  excerpt,
  story_type,
  location,
  tags,
  cultural_sensitivity_level,
  requires_elder_review,
  enable_ai_processing,
  notify_community,
  language,
  created_at;
